### ISSUE TITLE
Support for Robolectric

### ISSUE THREAD

**Issue by yschimke** [QuickBirdEng/kotlin-snapshot-testing#2]
Nice library, I'm using it here

https://github.com/joreilly/Confetti/pull/361/files#diff-ef1466c1be0cdb61ac6832d7b41f045a08a6b40341df424fb878a1e7eb7a6909

With Robolectric 4.10 alpha. https://github.com/robolectric/robolectric/releases/tag/robolectric-4.10-alpha-1

At the moment Robolectric doesn't support captureToImage. https://github.com/robolectric/robolectric/issues/8071

But flagging as it might be something to support with your library.

**Comment by balazstothofficial** [comment]
How exactly would you like to support it?
If you have a different way to take a screenshot, you can write a custom `Snappshotting`. You can do that like for the current capturing in: [composeScreenshot](https://github.com/QuickBirdEng/kotlin-snapshot-testing/blob/master/snapshot/src/androidMain/kotlin/com/quickbird/snapshot/Snapshotting%2BcomposeScreenshot.kt)
Depending on the way we could add it to the library.

Another fix could be to use the string tree instead of an image: [composeNodeStringTree](https://github.com/QuickBirdEng/kotlin-snapshot-testing/blob/master/snapshot/src/androidMain/kotlin/com/quickbird/snapshot/Snapshotting%2BcomposeStringTree.kt)

**Comment by yschimke** [comment]
Yep - that's in the PR I linked to

https://github.com/joreilly/Confetti/blob/main/wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/ScreenshotTest.kt#L107

```
            val snapshotting = Snapshotting(
                diffing = Diffing.bitmap(colorDiffing = Diffing.intMean),
                snapshot = { node: SemanticsNodeInteraction ->
                    Bitmap.createBitmap(view.width, view.height, Bitmap.Config.ARGB_8888).apply {
                        view.draw(Canvas(this))
                    }
                }
            ).fileSnapshotting
```

**Comment by yschimke** [comment]
Feel free to close if it's out of scope. But it feels like a really useful improvement for screenshot testing, so figured I'd raise this.

**Comment by balazstothofficial** [comment]
Ah, I didn't see that, really cool, I'll add it 👍🏻

**Comment by yschimke** [comment]
I hope they fix the captureToImage, but crucially, using your API it won't matter.  It will do the right thing.

**Comment by oas004** [comment]
It might not work entirely with shadows and `clipToOutline` as well https://github.com/robolectric/robolectric/issues/8081, or you have to do a workaround for that, not entirely sure. Might be worth keeping in mind at least :)

**Comment by yschimke** [comment]
@oas004 it's an alpha1, so I think some issues are to be expected. But I think it's likely to get better and better over time.

**Comment by oas004** [comment]
Yeah that is true, good point! :)

**Comment by balazstothofficial** [comment]
I added it: https://github.com/QuickBirdEng/kotlin-snapshot-testing/pull/5
